#!/bin/sh
# bootstrap -- build infra-structure
# EPSON ESC/P-R Printer Driver for Linux
# Copyright (C) Seiko Epson Corporation 2013.
#  This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110, USA.

if ! test -d m4 ; then
  mkdir m4
else
  rm -f m4/*
fi
cat /dev/null > aclocal.m4
cat /dev/null > m4-macros

libtoolize -c --force
aclocal -I m4 
autoconf && automake

